Repository volkamerlab/teachopencadd, pull requests merged in 2023-05, with the labels that each got.

#350 T018: deprecation warnings and images not showing (#334)
  devtools/test_env.yml
  teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/helpers/nglview.py
  teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/helpers/pdb.py
  teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/ligand.py
  teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/protein.py
Labels: work in progress, 2023.05.1 (master update)

#308 T019: Fix "No template found for residue 444 (03P)"
  .github/workflows/ci.yml
  teachopencadd/talktorials/T019_md_simulation/talktorial.ipynb
Labels: bug

#382 Docs CI: ignore some 403 in linkcheck
  .github/workflows/docs.yml
  teachopencadd/talktorials/T033_molecular_representations/talktorial.ipynb
  teachopencadd/talktorials/T037_uncertainty_estimation/talktorial.ipynb
Labels: documentation, 2023.05.2 (DL edition)
